### ISSUE TITLE
Change Parser of the new Repo Structure

### ISSUE THREAD

**Issue by wongband** [bitprj/bit-backend#111]
**Is your feature request related to a problem? Please describe.**
Old format in the curriculum repo needs an upgrade for better accessability.

**Describe the solution you'd like**
Change the structure of what gets parsed.

**Tasks to do in oder**
- [x] Redo CRUD routes for parsing topics. Topics now belong at the root repo with each folder being the Topic_Name.
- [x] Module Folders should only have readmes in there. Adjust CRUD routes for parsing modules.
- [x] Modules should now have two fields called activities and projects where they would be bullt pointed to be the path of the activities and projects
- [x] Activities and Projects still stay the same except they are under different folders. Adjust Parsing Activities/Projects

Change the documentation on Gitbooks and FetchRequests in Postman as each checkbox is completed.
